FIELDS:
    WIDTH:
        type: integer
        title:
            ru: Широта
        hint:
            ru: Введите широту в градусах (от -90 до 90), тип данных int
        min: -90
        max: 90
        default: 0

    LONG:
        type: integer
        title:
            ru: Долгота
        hint:
            ru: Введите долготу в градусах (от -180 до 180), тип данных int
        min: -180
        max: 180
        default: 0

    RADIUS:
        type: integer
        title:
            ru: Радиус области моделирования
        hint:
            ru: Введите радиус выбранной области в километрах (максимум-30), тип данных int
        default: 1
        max: 20000
        min: 1


    DATE:
        type: string
        title:  
            ru: Дата начала отсчёта
        hint:
            ru: Введите дату в вида дд.мм.гггг; Дата ОБЯЗАТЕЛЬНО должна быть в будущем; Не используйте буквы
        default: 01.01.2000

    START_TIME:
        type: string
        title:  
            ru: Время начала отсчёта
        hint:
            ru: Введите время в виде чч.мм.сс по Гринвичу; Время ОБЯЗАТЕЛЬНО должно быть в будущем; Не используйте буквы
        default: 00.00.00
    
    DURATION:
        type: integer
        title:  
            ru: Продолжительность моделирования
        hint:
            ru: Укажите промежуток времени в секундах, тип данных int
        default: 100
        min: 1
    
    STEP:
        type: integer
        hint:
            ru: Укажите временной шаг в секундах для моделирования, тип данных int
        title:
            ru: Шаг моделироввания
        default: 1


    TRASH_TYPE:
        type: boolean
        hint:
            ru: Выбрав этот пункт, вы получите в результате модель динамики мусора
        title:  
            ru: Космический Мусор
    
    SATELITE_TYPE:
        type: boolean
        hint:
            ru: Выбрав этот пункт, вы получите в результате модель динамики спутников
        title:
            ru: Спутник


    GRAPHIC_NAME:
        type: string
        title:  
            ru: Название графика
        hint:
            ru: Введите подпись графика
        default: test
    
    COLOR_SATELITE:
        type: string
        title:  
            ru: Цвет маркера
        hint:
            ru: Выберите из выпадающего списка цвет для обозначения маркеров спутников и мусора
        default: 'black'
        enum:
          - value: 'black'
            name:
              ru: Чёрный
          - value: 'red'
            name:
              ru: Красный
          - value: 'blue'
            name:
              ru: Синий
          - value: 'green'
            name:
              ru: Зелёный
          - value: 'yellow'
            name:
              ru: Жёлтый
          - value: 'pink'
            name:
              ru: Розовый  

    COLOR_DEBRIS:
        type: string
        title:  
            ru: Цвет маркера
        hint:
            ru: Выберите из выпадающего списка цвет для обозначения маркеров спутников и мусора
        default: 'black'
        enum:
          - value: 'black'
            name:
              ru: Чёрный
          - value: 'red'
            name:
              ru: Красный
          - value: 'blue'
            name:
              ru: Синий
          - value: 'green'
            name:
              ru: Зелёный
          - value: 'yellow'
            name:
              ru: Жёлтый
          - value: 'pink'
            name:
              ru: Розовый  

    MARKER_FORM_SATELITE:
        type: string
        title:  
            ru: Форма маркера
        hint:
            ru: Выберите форму маркера для обозначения на графике спутников и мусора
        default: 'o'
        enum:
            - value: 'o'
              name:
                  ru: Круг
            - value: 's'
              name:
                  ru: Квадрат
            - value: '*'
              name:
                  ru: Звезда
            - value: 'D'
              name:
                  ru: Ромб
            - value: 'x'
              name:
                  ru: X-образный

    MARKER_FORM_DEBRIS:
        type: string
        title:  
            ru: Форма маркера
        hint:
            ru: Выберите форму маркера для обозначения на графике спутников и мусора
        default: 'o'
        enum:
            - value: 'o'
              name:
                  ru: Круг
            - value: 's'
              name:
                  ru: Квадрат
            - value: '*'
              name:
                  ru: Звезда
            - value: 'D'
              name:
                  ru: Ромб
            - value: 'x'
              name:
                  ru: X-образный

    MARKER_SIZE_SATELITE:
        type: integer
        title:  
            ru: Размер маркера
        hint:
            ru: Введите число для обозначения размера, int
        default: 5

    MARKER_SIZE_DEBRIS:
        type: integer
        title:  
            ru: Размер маркера
        hint:
            ru: Введите число для обозначения размера, int
        default: 5

    LINE_STYLE_SATELITE:
        type: string
        title:  
            ru: Стиль линии
        hint:
            ru: Выберите стиль траекторий, которые будут рисоваться выбранными вами объектами моделирования
        default: '-'
        enum:
            - value: '-'
              name:
                  ru: Сплошная линия
            - value: '--'
              name:
                  ru: Штриховая линия
            - value: '-.'
              name:
                  ru: Штрих-пунктирная линия
            - value: ':'
              name:
                  ru: Пунктирная линия

    LINE_STYLE_DEBRIS:
        type: string
        title:  
            ru: Стиль линии
        hint:
            ru: Выберите стиль траекторий, которые будут рисоваться выбранными вами объектами моделирования
        default: '-'
        enum:
            - value: '-'
              name:
                  ru: Сплошная линия
            - value: '--'
              name:
                  ru: Штриховая линия
            - value: '-.'
              name:
                  ru: Штрих-пунктирная линия
            - value: ':'
              name:
                  ru: Пунктирная линия

    # выпадающий список
    TYPE_OF_FILE:
        type: string
        title:  
            ru: Тип файла
        hint:
            ru: Выберите подходящее под ваши цели расширение файла
        enum:
            - value: '.png'
              name:
                  ru: .png
            - value: '.gif'
              name:
                  ru: .gif
        default: '.png'


    USER_SATELITE:
        title:
          ru: Запуск пользовательских спутников
        type: object
        FIELDS:
            WIDTH_SAT:
                type: integer
                title:
                    ru: Широта
                hint:
                    ru: Введите широту в градусах, тип данных int
                min: -90
                max: 90
                default: 0

            LONG_SAT:
                type: integer
                title:
                    ru: Долгота
                hint:
                    ru: Введите долготу в градусах, тип данных int
                min: -180
                max: 180
                default: 0

            ABS_VELOCITY:
                title:
                    ru: Модуль скорости
                type: decimal
                hint:
                    ru: Направление скорости радиальное
                min: 0
                max: 20000
                default: 11800
            
            COLOR_SAT:
                type: string
                title:  
                    ru: Цвет маркера
                default: 'black'
                hint:
                    ru: Выберите из выпадающего списка цвет для обозначения маркера ВАШИХ аппартов на графике.
                enum:
                    - value: 'black'
                      name:
                        ru: Чёрный
                    - value: 'red'
                      name:
                        ru: Красный
                    - value: 'blue'
                      name:
                        ru: Синий
                    - value: 'green'
                      name:
                        ru: Зелёный
                    - value: 'yellow'
                      name:
                        ru: Жёлтый
                    - value: 'pink'
                      name:
                        ru: Розовый
        STRUCTURE:
            - group:
                key: user_satelite
                title:
                  ru: Добавить
                fields:
                    - field: WIDTH_SAT
                    - field: LONG_SAT
                    - field: ABS_VELOCITY
                    - field: COLOR_SAT
                      width: full


STRUCTURE:
    - group:
        key: main_settings
        title:  
            ru: Общие настройки
        fields:
            - separator:
                title:
                  ru: Координаты            
            - field: WIDTH
            - field: LONG
            - field: RADIUS
            - separator:
                title:
                  ru: Время
            - field: DATE
            - field: START_TIME
            - field: DURATION
            - field: STEP
            - separator:
                title:
                  ru: Тип объекта моделирования
            - field: TRASH_TYPE
              width: full
            - field: SATELITE_TYPE
              width: full        
    
    - group:
        key: graf_settings
        title:  
            ru: Настройки графика
        fields:
            - field: GRAPHIC_NAME
            - field: TYPE_OF_FILE
            - separator:
                title:
                  ru: Настроки отображения Мусора
            - field: COLOR_DEBRIS
              view: dropdown
            - field: MARKER_FORM_DEBRIS
              view: dropdown
            - field: MARKER_SIZE_DEBRIS
            - field: LINE_STYLE_DEBRIS
              view: dropdown
            - separator:
                title:
                  ru: Настроки отображения спутников
            - field: COLOR_SATELITE
              view: dropdown
            - field: MARKER_FORM_SATELITE
              view: dropdown
            - field: MARKER_SIZE_SATELITE
            - field: LINE_STYLE_SATELITE
              view: dropdown


    - group:
        key: user_satelites
        title:
            ru: Добавление спутников
        fields:
            - field: USER_SATELITE
              width: full

UNITS:
    length:
      km:
        m: 1000
        title:
          ru: километры
      m:
        km: 0.001
        title:
          ru: Метры